services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: trivia
      POSTGRES_USER: kokoa
      POSTGRES_PASSWORD: kokoa
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql